# Release Drafter configuration: shared categories and naming defaults for automated release notes.
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Fixes'
    labels: ['bug', 'fix']
  - title: '🧰 Maintenance'
    labels: ['chore', 'dependencies', 'maintenance']
  - title: '🛡 Security'
    labels: ['security']

replacers:
  - search: '^## What's Changed'
    replace: '## What''s Changed'

exclude-labels:
  - 'skip-release'

auto-labeler:
  - label: 'dependencies'
    branch:
      - '/dependabot\//'

prerelease: false
