name: "Bug report"
description: "Report a reproducible problem"
labels:
  - bug
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve! Review the [support policy](../../SUPPORT.md) and [Code of Conduct](../../CODE_OF_CONDUCT.md) before submitting.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: "What happened?"
      placeholder: "The login form fails when..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "List the exact steps so we can reproduce the issue."
      placeholder: "1. Go to...\n2. Click...\n3. Observe..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / logs
      description: "Include error messages, screenshots, or logs if available."
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Version info, OS, browsers, deployments, feature flags."
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: "I have searched existing issues."
          required: true
        - label: "I agree to follow the Code of Conduct."
          required: true
