blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: mailto:security@example.org
    about: "Report sensitive security issues privately. See SECURITY.md for details."
  - name: Support policy
    url: https://github.com/org/.github/blob/main/SUPPORT.md
    about: "Understand response expectations before filing an issue."
